#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v27
# autospec commit: 65cf152
#
Name     : R-analogue
Version  : 0.18.1
Release  : 60
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/analogue_0.18.1.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/analogue_0.18.1.tar.gz
Summary  : Analogue and Weighted Averaging Methods for Palaeoecology
Group    : Development/Tools
License  : GPL-2.0
Requires: R-analogue-lib = %{version}-%{release}
Requires: R-analogue-license = %{version}-%{release}
Requires: R-brglm
Requires: R-princurve
Requires: R-vegan
BuildRequires : R-brglm
BuildRequires : R-princurve
BuildRequires : R-vegan
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
function models for prediction of environmental data from species
	     data, and related methods used in palaeoecology.

%package lib
Summary: lib components for the R-analogue package.
Group: Libraries
Requires: R-analogue-license = %{version}-%{release}

%description lib
lib components for the R-analogue package.


%package license
Summary: license components for the R-analogue package.
Group: Default

%description license
license components for the R-analogue package.


%prep
%setup -q -n analogue
pushd ..
cp -a analogue buildavx2
popd
pushd ..
cp -a analogue buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1750884841

%install
export SOURCE_DATE_EPOCH=1750884841
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/R-analogue
cp %{_builddir}/analogue/inst/COPYING %{buildroot}/usr/share/package-licenses/R-analogue/55ff89965535a854d98092805b33577fa49d40bf || :
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/analogue/CITATION
/usr/lib64/R/library/analogue/COPYING
/usr/lib64/R/library/analogue/ChangeLog
/usr/lib64/R/library/analogue/DESCRIPTION
/usr/lib64/R/library/analogue/INDEX
/usr/lib64/R/library/analogue/Meta/Rd.rds
/usr/lib64/R/library/analogue/Meta/data.rds
/usr/lib64/R/library/analogue/Meta/features.rds
/usr/lib64/R/library/analogue/Meta/hsearch.rds
/usr/lib64/R/library/analogue/Meta/links.rds
/usr/lib64/R/library/analogue/Meta/nsInfo.rds
/usr/lib64/R/library/analogue/Meta/package.rds
/usr/lib64/R/library/analogue/Meta/vignette.rds
/usr/lib64/R/library/analogue/NAMESPACE
/usr/lib64/R/library/analogue/NEWS
/usr/lib64/R/library/analogue/ONEWS.Rd
/usr/lib64/R/library/analogue/R/analogue
/usr/lib64/R/library/analogue/R/analogue.rdb
/usr/lib64/R/library/analogue/R/analogue.rdx
/usr/lib64/R/library/analogue/THANKS
/usr/lib64/R/library/analogue/TODO
/usr/lib64/R/library/analogue/data/Biome.rda
/usr/lib64/R/library/analogue/data/Climate.rda
/usr/lib64/R/library/analogue/data/ImbrieKipp.rda
/usr/lib64/R/library/analogue/data/Location.rda
/usr/lib64/R/library/analogue/data/Pollen.rda
/usr/lib64/R/library/analogue/data/Salinity.rda
/usr/lib64/R/library/analogue/data/SumSST.rda
/usr/lib64/R/library/analogue/data/V12.122.rda
/usr/lib64/R/library/analogue/data/WinSST.rda
/usr/lib64/R/library/analogue/data/abernethy.rda
/usr/lib64/R/library/analogue/data/rlgh.rda
/usr/lib64/R/library/analogue/data/swapdiat.rda
/usr/lib64/R/library/analogue/data/swappH.rda
/usr/lib64/R/library/analogue/data/tortula.rda
/usr/lib64/R/library/analogue/doc/analogue_methods.R
/usr/lib64/R/library/analogue/doc/analogue_methods.Rnw
/usr/lib64/R/library/analogue/doc/analogue_methods.pdf
/usr/lib64/R/library/analogue/doc/index.html
/usr/lib64/R/library/analogue/help/AnIndex
/usr/lib64/R/library/analogue/help/aliases.rds
/usr/lib64/R/library/analogue/help/analogue.rdb
/usr/lib64/R/library/analogue/help/analogue.rdx
/usr/lib64/R/library/analogue/help/paths.rds
/usr/lib64/R/library/analogue/html/00Index.html
/usr/lib64/R/library/analogue/html/R.css
/usr/lib64/R/library/analogue/tests/Examples/analogue-Ex.Rout.save
/usr/lib64/R/library/analogue/tests/test-all.R
/usr/lib64/R/library/analogue/tests/testthat/test-Stratiplot.R
/usr/lib64/R/library/analogue/tests/testthat/test-analog.R
/usr/lib64/R/library/analogue/tests/testthat/test-join.R
/usr/lib64/R/library/analogue/tests/testthat/test-new-distance.R
/usr/lib64/R/library/analogue/tests/testthat/test-tran.R

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/analogue/libs/analogue.so
/V4/usr/lib64/R/library/analogue/libs/analogue.so
/usr/lib64/R/library/analogue/libs/analogue.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/R-analogue/55ff89965535a854d98092805b33577fa49d40bf
